name: llamabot
channels:
- conda-forge
dependencies:
# Core stack
- python=3.9
- build
- bump2version
- ipykernel
- ipywidgets
- jupyter
- jupyterlab
- mamba
- pip
- twine
# Utilities
- pyprojroot
- python-dotenv
# CLI development
- typer
# Software testing
- hypothesis
- pytest
# Code Style Tools
- black
- darglint
- flake8
- interrogate
- pre-commit
- pylint
# Documentation
- mkdocs
- mkdocs-material
- mkdocstrings
- panel
- jupyter_bokeh
# pip dependencies
- pip:
  # Place packages that cannot be installed by conda in this section.
  - openai
  - langchain
  - mknotebooks
  - wget
