name: llamabot
channels:
  - conda-forge
dependencies:
  # Core stack
  - python=3.11
  - build
  - bump2version
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - mamba
  - pip
  - twine
  - loguru
  - numpy<2 # Added temporarily on 29 May 2024; see https://github.com/ericmjl/llamabot/issues/56
  - sentence-transformers
  # Utilities
  - pyprojroot
  - python-dotenv
  # CLI development
  - typer>=0.4.0
  # Software testing
  - hypothesis>=6.99.6
  - pytest
  - pytest-cov
  - coverage
  # Code Style Tools
  - black
  - darglint
  - flake8
  - interrogate
  - pylint
  # Documentation
  - mkdocs=1.4.3
  - mkdocs-material
  - mkdocstrings
  - panel
  - jupyter_bokeh
  - bokeh
  - pyzotero
  - pyperclip
  - astunparse
  - pytest-mock
  - gitpython
  - textual
  - prompt-toolkit
  - openai
  - wget
  - rich
  - pyzotero
  - nltk # transitive dependency by way of llama_index
  - chromadb
  - python-slugify
  # pip dependencies
  - pip:
      # Place packages that cannot be installed by conda in this section.
      - mknotebooks
      - case-converter
      - sh
      - unstructured[all-docs]
      - litellm<=1.35.38
      - pydantic>=2.0
      - pdfminer.six
      - rank-bm25
      - lancedb
