name: Build development container

on:
    schedule:
        # Cron schedule every morning at 3.14 am
        - cron: '14 3 * * *'

jobs:
    if: github.owner == "ericmjl"
    build-container:


        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2

        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v3

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        -   name: Build and push
            uses: docker/build-push-action@v6
            with:
                push: true
                tags: ericmjl/llamabot-devcontainer:latest,ericmjl/llamabot-devcontainer:${{ github.sha }}
                file: .devcontainer/Dockerfile
                cache-from: type=gha
                cache-to: type=gha,mode=max
